title: Hello, world! I'm Ethan Sorensen
description: > # this means to ignore newlines until "the next field:"
  Portfolio site for Ethan Sorensen.
permalink: ':title/'
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com --> https://www.esorensen.dev to be
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ethan Sorensen # add your name
author-img: ethan-sorensen_temp.png # add your photo
about-author: >
  Hi there! I'm a BYU Student currently in junior core. 
  I love tackling new, challenging problems. I'm also a fanatic of the outdoors.
  Click the links below to download my resume, view my CV and projects, or get
  in touch with me. Otherwise, feel free to look around.
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: EpicPantalones # add your Github handle
social-linkedin: ethan-na-sorensen # add your Linkedin handle
social-email: ethansorensen01@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
